"""empty message

Revision ID: 6863ce4fda1d
Revises: c6fbe11d2ef8
Create Date: 2020-07-18 01:49:29.519444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6863ce4fda1d'
down_revision = 'c6fbe11d2ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('name', sa.VARCHAR(length=70), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
